spring:
  application:
    name: cliente-productos
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8090

config:
  base:
    #urlProducto: http://localhost:8080/api/v2/productos
    urlProducto: http://spring-webflux-rest-crud/api/v2/productos
    endpoint-v2: /api/v2/productos
    endpoint: /api/productos
logging:
  level:
    web: debug