spring:
  application:
    name: cliente-productos
server:
  port: 8090

config:
  base:
    urlProducto: http://localhost:8080/api/v2/productos
    endpoint-v2: /api/v2/productos
    endpoint: /api/productos
logging:
  level:
    web: debug